
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gowtham19.bm@gmail.com
    password: dyfwnlkoqwddbwro
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true